### ISSUE TITLE
Comment all the parameters

### ISSUE THREAD

**Issue by filmenczer** [IUNetSci/DrifterBot#3]
For **any and all** parameter that the user needs to enter, we need a very clear explanation of what the parameter means, what are the possible values, and some example.

**Comment by filmenczer** [comment]
Be sure to have ALL parameters in a single file. Eg, move the params in `others/init_bot_info.py` to `bot/config_stats.py` and comment them. Import them from `others/init_bot_info.py`.

**Comment by roisevege** [comment]
Updated. Could you check?
