### ISSUE TITLE
update data dump

### ISSUE THREAD

**Issue by filmenczer** [IUNetSci/DrifterBot#4]
`tweet_scores_hashed.csv.zip` in data folder needs to be updated with the low-credibility counts

**Comment by roisevege** [comment]
@diogofpacheco I updated the file.Could you check whether its format is correct?

**Comment by diogofpacheco** [comment]
Just the first file has a header. Is that something expected?

**Comment by roisevege** [comment]
It's expected. It was caused by the way I split the data file. I think it's unnecessary to keep the header in the first file, so I remove it. 
I added a readme file in that folder to explain what each column is.
