### ISSUE TITLE
Script/notebook to analyze algorithmic bias

### ISSUE THREAD

**Issue by filmenczer** [IUNetSci/DrifterBot#5]
Add script/notebook for statistical analysis of algorithmic bias (Table S2).

**Comment by yang3kc** [comment]
Changes:

1. Add https://github.com/IUNetSci/DrifterBot/blob/master/exps/algorithm_bias_estimation.ipynb 
2. Modify readme in home directory, see https://github.com/IUNetSci/DrifterBot/commit/949048140b5491405209cde7b4a70083144ab5f9 for details
3. Modify readme in `exps` directory, see https://github.com/IUNetSci/DrifterBot/commit/66dfb21ecdc70215443d614b99d513beefcbade4#diff-a39e19691dd82cab2047ca89c43b2fac for details
